version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 21
  pre_build:
    commands:
      - echo "Installing dependencies"
      - ls -la
      - cd doc
      - npm install
  build:
    commands:
      - echo "Building the application"
      - npm run docs:build
  post_build:
    commands:
      - mkdir dist
      - cp -R src/.vuepress/dist/* dist
      - echo $CODEBUILD_SRC_DIR
      - ls -la $CODEBUILD_SRC_DIR
artifacts:
  files:
    - dist/**/*
